# Generated by Django 5.2.5 on 2025-09-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=20)),
                ('track_id', models.CharField(max_length=20)),
                ('from_station', models.CharField(max_length=20)),
                ('to_station', models.CharField(max_length=20)),
                ('start_min', models.IntegerField()),
                ('end_min', models.IntegerField()),
                ('duration_min', models.IntegerField()),
                ('priority', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
