# Generated by Django 5.1.7 on 2025-10-14 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_id', models.CharField(editable=False, help_text='Automatically generated unique freight identifier', max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of material in specified units', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('in_transit', 'In Transit'), ('loading', 'Loading'), ('unloading', 'Unloading'), ('reloading', 'Reloading'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='free', help_text='Current status of the freight', max_length=20)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('predicted_delay', models.BooleanField(default=False)),
                ('delay_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('route_complexity', models.IntegerField(blank=True, null=True)),
                ('tracking_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Freight Booking',
                'verbose_name_plural': 'Freight Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='tons', max_length=20)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Route Complexity',
                'verbose_name_plural': 'Route Complexities',
                'ordering': ['complexity_score'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Railway Station',
                'verbose_name_plural': 'Railway Stations',
                'ordering': ['name'],
            },
        ),
    ]
