# Generated by Django 4.2.24 on 2025-09-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_destinations', to='booking.station'),
        ),
        migrations.AddField(
            model_name='freight',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.materialtype'),
        ),
        migrations.AddField(
            model_name='freight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_origins', to='booking.station'),
        ),
        migrations.AlterUniqueTogether(
            name='routecomplexity',
            unique_together={('origin', 'destination')},
        ),
    ]
