# Generated by Django 5.1.7 on 2025-10-14 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freight',
            name='material_type',
            field=models.ForeignKey(help_text='Type of material being transported', on_delete=django.db.models.deletion.CASCADE, to='booking.materialtype'),
        ),
        migrations.AddField(
            model_name='routecomplexity',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='booking.station'),
        ),
        migrations.AddField(
            model_name='routecomplexity',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origins', to='booking.station'),
        ),
        migrations.AddField(
            model_name='freight',
            name='destination',
            field=models.ForeignKey(help_text='Destination station for the freight', on_delete=django.db.models.deletion.CASCADE, related_name='freight_destinations', to='booking.station'),
        ),
        migrations.AddField(
            model_name='freight',
            name='origin',
            field=models.ForeignKey(help_text='Origin station for the freight', on_delete=django.db.models.deletion.CASCADE, related_name='freight_origins', to='booking.station'),
        ),
        migrations.AlterUniqueTogether(
            name='routecomplexity',
            unique_together={('origin', 'destination')},
        ),
    ]
