# Generated by Django 4.2.24 on 2025-10-21 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freight',
            options={'ordering': ['-created_at'], 'verbose_name': 'Freight Booking', 'verbose_name_plural': 'Freight Bookings'},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ['name'], 'verbose_name': 'Material Type', 'verbose_name_plural': 'Material Types'},
        ),
        migrations.AlterModelOptions(
            name='routecomplexity',
            options={'ordering': ['complexity_score'], 'verbose_name': 'Route Complexity', 'verbose_name_plural': 'Route Complexities'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name'], 'verbose_name': 'Railway Station', 'verbose_name_plural': 'Railway Stations'},
        ),
        migrations.AlterField(
            model_name='freight',
            name='destination',
            field=models.ForeignKey(help_text='Destination station for the freight', on_delete=django.db.models.deletion.CASCADE, related_name='freight_destinations', to='booking.station'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='freight_id',
            field=models.CharField(editable=False, help_text='Automatically generated unique freight identifier', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='freight',
            name='material_type',
            field=models.ForeignKey(help_text='Type of material being transported', on_delete=django.db.models.deletion.CASCADE, to='booking.materialtype'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='origin',
            field=models.ForeignKey(help_text='Origin station for the freight', on_delete=django.db.models.deletion.CASCADE, related_name='freight_origins', to='booking.station'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of material in specified units', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='freight',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('in_transit', 'In Transit'), ('loading', 'Loading'), ('unloading', 'Unloading'), ('reloading', 'Reloading'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='free', help_text='Current status of the freight', max_length=20),
        ),
    ]
