# Generated by Django 4.2.25 on 2025-10-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_freight_options_alter_materialtype_options_and_more'),
        ('booking', '0003_fix_created_by'),
    ]

    operations = [
    ]
