# Generated by Django 5.2.5 on 2025-09-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayWorker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('assigned_station', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'railway_workers',
            },
        ),
        migrations.CreateModel(
            name='RealTimeDelay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('train_number', models.CharField(max_length=20)),
                ('station_code', models.CharField(max_length=10)),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'realtime_delay',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('station_name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('platforms', models.IntegerField(default=1)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_station_id', models.CharField(max_length=10)),
                ('destination_station_id', models.CharField(max_length=10)),
                ('distance_km', models.FloatField()),
                ('track_type', models.CharField(default='unknown', max_length=50)),
                ('electrification', models.BooleanField(default=False)),
                ('speed_limit', models.IntegerField(default=90, help_text='Speed limit in km/h')),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=255)),
                ('source_station', models.CharField(max_length=10)),
                ('destination_station', models.CharField(max_length=10)),
                ('total_coaches', models.IntegerField(default=12)),
            ],
            options={
                'db_table': 'trains',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('work_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('signal_operator', 'Signal Operator'), ('maintenance', 'Maintenance Crew'), ('station_staff', 'Station Staff'), ('admin', 'Administrator')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
