# Generated by Django 5.2.6 on 2025-09-24 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('station_name', models.CharField(max_length=255)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('platforms', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('train_name', models.CharField(max_length=255)),
                ('train_type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_route', models.TextField(blank=True, null=True)),
                ('coach_length', models.IntegerField(default=12)),
                ('max_speed_kmph', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('work_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('station_master', 'Station Master'), ('section_controller', 'Section Controller'), ('freight_operator', 'Freight Operator'), ('track_manager', 'Track Manager')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RailwayWorker',
            fields=[
                ('govt_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('freight_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('track_status', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_impact', models.CharField(blank=True, max_length=100, null=True)),
                ('freight_type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=50, null=True)),
                ('coach_length', models.IntegerField(blank=True, null=True)),
                ('max_speed_kmph', models.IntegerField(blank=True, null=True)),
                ('delayed_flag', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('current_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('distance_km', models.FloatField()),
                ('track_type', models.CharField(default='unknown', max_length=50)),
                ('electrification', models.BooleanField(default=False)),
                ('speed_limit', models.IntegerField(default=90, help_text='Speed limit in km/h')),
                ('status', models.CharField(default='active', max_length=50)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_to', to='core.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_from', to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_min', models.IntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_departures', to='core.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_arrivals', to='core.station')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('track_status', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_impact', models.CharField(blank=True, max_length=100, null=True)),
                ('train_type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=50, null=True)),
                ('coach_length', models.IntegerField(blank=True, null=True)),
                ('max_speed_kmph', models.IntegerField(blank=True, null=True)),
                ('delayed_flag', models.BooleanField(default=False)),
                ('current_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
        ),
    ]
