# Generated by Django 5.2.6 on 2025-09-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='work_id',
            new_name='govt_id',
        ),
    ]
