# Generated by Django 5.2.5 on 2025-09-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedelay',
            name='predicted_delay',
            field=models.FloatField(default=0),
        ),
    ]
