# Generated by Django 5.2.6 on 2025-09-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_work_id_employee_govt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedelay',
            name='coach_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtimedelay',
            name='max_speed_kmph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
