# Generated by Django 4.2.24 on 2025-09-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250908_0034'),
    ]

    operations = [
    ]
