# Generated by Django 4.2.24 on 2025-09-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250920_0905'),
    ]

    operations = [
    ]
