# Generated by Django 4.2.24 on 2025-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250920_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('control_officer', 'Control Officer'), ('divisional_traffic_manager', 'Divisional Traffic Manager'), ('station_master', 'Station Master'), ('yard_master', 'Yard Master'), ('signal_inspector', 'Signal Inspector'), ('loco_pilot', 'Loco Pilot'), ('assistant_loco_pilot', 'Assistant Loco Pilot'), ('gatekeeper', 'Gatekeeper'), ('pointsman', 'Pointsman')], max_length=50),
        ),
    ]
