# Generated by Django 4.2.24 on 2025-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwayworker',
            name='govt_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
