# Generated by Django 5.2.6 on 2025-09-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_railwayworker_govt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('station_master', 'Station Master'), ('section_controller', 'Section Controller'), ('freight_operator', 'Freight Operator'), ('track_manager', 'Track Manager')], max_length=50),
        ),
    ]
